[theme]

# Primary accent for interactive elements
primaryColor = '#4AC38A'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#35A69B'

# Color used for almost all text
textColor = '#273346'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
